# Generated by Django 4.2.1 on 2023-05-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_auto_20190703_0259"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(
                default="请描述一下自己吧",
                help_text="请描述一下自己吧",
                max_length=200,
                verbose_name="个人描述",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "男"), ("female", "女")],
                default="男",
                help_text="gender/性别",
                max_length=32,
                verbose_name="性别",
            ),
        ),
    ]
