# Generated by Django 4.2 on 2023-05-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_cltnovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cltnovel',
            name='c_tintroduce',
            field=models.CharField(default='请描述一下自己吧', max_length=256, verbose_name='收藏帖子简介'),
        ),
        migrations.AddField(
            model_name='cltnovel',
            name='c_tphoto',
            field=models.CharField(default='请描述一下自己吧', max_length=128, null=True, verbose_name='收藏帖子图片'),
        ),
        migrations.AddField(
            model_name='cltnovel',
            name='c_ttitle',
            field=models.CharField(default='请描述一下自己吧', max_length=64, verbose_name='收藏帖子标题'),
        ),
        migrations.AlterField(
            model_name='cltnovel',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='收藏创建时间'),
        ),
    ]
