# Generated by Django 4.2 on 2023-05-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_cltnovel_c_tintroduce_cltnovel_c_tphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cltnovel',
            name='c_tintroduce',
            field=models.CharField(max_length=256, verbose_name='收藏帖子简介'),
        ),
        migrations.AlterField(
            model_name='cltnovel',
            name='c_tphoto',
            field=models.CharField(max_length=128, null=True, verbose_name='收藏帖子图片'),
        ),
        migrations.AlterField(
            model_name='cltnovel',
            name='c_ttitle',
            field=models.CharField(max_length=64, verbose_name='收藏帖子标题'),
        ),
    ]
